// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config'

export default defineConfig({
  datasourceUrl: "postgresql://neondb_owner:npg_tosJk6exU7gp@ep-royal-heart-ad54vle7-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
})